Ibrahim/648 lazy loading videojs dynamic import
mitodl/ocw-hugo-themes pull request #1089
Opened 2023-02-21 10:59 UTC by ibrahimjaved12

#### Pre-Flight checklist

- [ ] Screenshots and design review for any changes that affect layout or styling
  - [ ] Desktop screenshots
  - [ ] Mobile width screenshots
- [ ] Testing
  - [ ] Code is tested
  - [ ] Changes have been manually tested

#### What are the relevant tickets?
closes #648 

#### What's this PR do?
This PR implements lazy loading for videojs and its dependencies using dynamic imports. It also uses promise-polyfill for IE11 support.

#### How should this be manually tested?
(Required)

#### Where should the reviewer start?
(Optional)

#### Any background context you want to provide?
This PR is a WIP and cannot be manually tested yet, as a webpack issue is a blocker (development publicPath being 3000 instead of 3001).

#### Screenshots (if appropriate)
(Optional)

2023-03-07 14:04 UTC, ibrahimjaved12 commented
This PR (dynamic import functionality) is on hold because of webpack config need to be updated: https://github.com/mitodl/ocw-hugo-themes/pull/1102
But I believe the work here is done for this PR.
Once the webpack config PR is merged with main, I'll update this PR with instructions to test.

2023-03-17 09:36 UTC, HussainTaj-arbisoft requested changes
I ran into a bit of trouble while following the instructions. In the future, it would be great if you can mention the course id that we should test the change on. It would also be great if you could share some instructions about the environment, like "test in incognito" or "clear cache".

2023-03-17 09:43 UTC, ibrahimjaved12 commented on base-theme/layouts/partials/youtube_player.html
> +    window.initVideoJS()
Done

2023-03-17 09:49 UTC, ibrahimjaved12 commented
Thanks for the suggestions @HussainTaj-arbisoft. I have also updated the post with the testing suggestions.

2023-03-17 10:09 UTC, HussainTaj-arbisoft approved these changes
LGTM :+1:

2023-03-17 10:55 UTC, merged