Playwright video tests added - Start/End time - Transcript time
mitodl/ocw-hugo-themes pull request #1139
Opened 2023-05-05 10:28 UTC by fakhar-ud-din

#### Pre-Flight checklist

- [x] Testing
  - [x] Code is tested
  - [x] Changes have been manually tested

#### What are the relevant tickets?
Closes #1127

#### What's this PR do?
This PR adds playwright tests in hugo-themes for video start and end times as well as start time of the transcripts.

#### How should this be manually tested?
- Download captions file from https://live-qa.ocw.mit.edu/courses/8-01sc-classical-mechanics-fall-2016/917263bef37857bd94ef67692405bcc9_ErlP_SBcA1s.vtt
- Make a new path in local minio draft bucket
   - `ocw-content-draft/courses/123-ocw-ci-test-course-fall-2022`
- Upload the captions file in the above path
- Make sure the bucket's access policy is `public`
   - You can check this from `buckets -> bucket-name -> Access Policy`
- Run the following command in ocw-hugo-themes,
   - yarn test:e2e
- All tests should be successful

2023-05-08 21:13 UTC, ChristopherChudzicki requested changes
**Overall Comment:** Nice. And very cool that we can use Playwright to interact with the Iframe. I wasn't expecting that to work. I don't think we should be manipulating the iframe a whole lot in our tests, but since the Iframe controls code we do own (e.g., transcript), it seems appropriate.

**Requested Change:** Now that we understand the play button issue better, let's do the appropriate waiting without an explicit timeout.

**Suggestion:** I'd also like to suggest that you organize some of the video interaction code into a ["Page object model"](https://playwright.dev/docs/pom). Maybe something like this:

```ts
class VideoSection {
  private readonly page: Page

  constructor(page: Page) {
    this.page = page
  }

  /**
   * Returns a playwright locator for the video section of the page, containing
   * the video player itself as well as transcript / expandable tabs.
   * 
   * @fakhar goal here is to scope other the selectors to this part of the DOM.
   */
  videoSection(): Locator {
    return this.page.locator(".video-page")
  }

  /**
   * @returns Returns a video section Iframe.
   */
  iframe(): Locator {
    return this.videoSection().locator(
      'role=region[name="Video Player"] >> iframe'
    )
  }

  frameLocator(): FrameLocator {
    return this.iframe().frameLocator(":scope")
  }

  /**
   * @fakhar This is one way we can wait for the video player to be ready.
   * Use as `await videoSectionInstance().expectPlayerReady()`.
   *
   * NOTE!!! Requires updating Playright; 1.27 does not have expect(...).toPass()
   * as far as I can tell.
   */
  async expectPlayerReady(): Promise<void> {
    await expect(async () => {
      const readyState = await this.frameLocator()
        .locator("*")
        .first()
        .evaluate(() => window.document.readyState)
      expect(readyState).toEqual("complete")
    }).toPass()
  }

  playButton(): Locator {
    return this.frameLocator().getByRole("button", { name: "Play" })
  }

  transcript = {
    lines:      () => this.videoSection().locator(".transcript-line"),
    activeLine: () => this.transcript.lines().locator(".is-active")
  }
}
```

A few reasons I think the "page object model" approach is worthwhile:
1. automate common tasks (waiting for iframe to be ready could be common)
2. Gives a natural place to add explanatory comments (an explanation about `expectPlayerReady` is definitely worthwhile.)
3. Isolates CSS selectors. In general, I think we should avoid CSS-based Playwright selectors (preferring `byRole`). But sometimes they are most convenient. Like asserting about `.transcript-line` But CSS selectors are more fragile. Putting the CSS Selectors in a centralized place makes easier to fix issues down the road if classnames change or something.

2023-05-08 21:13 UTC, ChristopherChudzicki requested changes
**Overall Comment:** Nice. And very cool that we can use Playwright to interact with the Iframe. I wasn't expecting that to work. I don't think we should be manipulating the iframe a whole lot in our tests, but since the Iframe controls code we do own (e.g., transcript), it seems appropriate.

**Requested Change:** Now that we understand the play button issue better, let's do the appropriate waiting without an explicit timeout.

**Suggestion:** I'd also like to suggest that you organize some of the video interaction code into a ["Page object model"](https://playwright.dev/docs/pom). Maybe something like this:

```ts
class VideoSection {
  private readonly page: Page

  constructor(page: Page) {
    this.page = page
  }

  /**
   * Returns a playwright locator for the video section of the page, containing
   * the video player itself as well as transcript / expandable tabs.
   * 
   * @fakhar goal here is to scope other the selectors to this part of the DOM.
   */
  videoSection(): Locator {
    return this.page.locator(".video-page")
  }

  /**
   * @returns Returns a video section Iframe.
   */
  iframe(): Locator {
    return this.videoSection().locator(
      'role=region[name="Video Player"] >> iframe'
    )
  }

  frameLocator(): FrameLocator {
    return this.iframe().frameLocator(":scope")
  }

  /**
   * @fakhar This is one way we can wait for the video player to be ready.
   * Use as `await videoSectionInstance().expectPlayerReady()`.
   *
   * NOTE!!! Requires updating Playright; 1.27 does not have expect(...).toPass()
   * as far as I can tell.
   */
  async expectPlayerReady(): Promise<void> {
    await expect(async () => {
      const readyState = await this.frameLocator()
        .locator("*")
        .first()
        .evaluate(() => window.document.readyState)
      expect(readyState).toEqual("complete")
    }).toPass()
  }

  playButton(): Locator {
    return this.frameLocator().getByRole("button", { name: "Play" })
  }

  transcript = {
    lines:      () => this.videoSection().locator(".transcript-line"),
    activeLine: () => this.transcript.lines().locator(".is-active")
  }
}
```

A few reasons I think the "page object model" approach is worthwhile:
1. automate common tasks (waiting for iframe to be ready could be common)
2. Gives a natural place to add explanatory comments (an explanation about `expectPlayerReady` is definitely worthwhile.)
3. Isolates CSS selectors. In general, I think we should avoid CSS-based Playwright selectors (preferring `byRole`). But sometimes they are most convenient. Like asserting about `.transcript-line` But CSS selectors are more fragile. Putting the CSS Selectors in a centralized place makes easier to fix issues down the road if classnames change or something.

2023-05-10 11:14 UTC, fakhar-ud-din commented on tests-e2e/ocw-ci-test-course/shortcodes.spec.ts
> +    .getAttribute("style")
This was added to ensure that the video thumbnail loads, indicating player has finished loading.

2023-05-10 13:58 UTC, ChristopherChudzicki requested changes
Looks good, a few small organization requests

2023-05-10 13:58 UTC, ChristopherChudzicki commented on tests-e2e/ocw-ci-test-course/shortcodes.spec.ts
> +  const src = await page.locator("iframe.vjs-tech").getAttribute("src")
```suggestion
  const src = await videoSection.iframe().getAttribute("src")
```

Nicer to not use the `.vjs-tech` class. *There's still a class in the `VideoSection` class used for scoping the locators, but that CSS class is ours, and if it changes, we only need to change it in one spot, namely VideoSection.*

IMO, worth making this change in the other tests, too.

2023-05-10 13:58 UTC, ChristopherChudzicki commented on tests-e2e/util/VideoSection.ts
> +class VideoSection {
**Requested Change:** Could you merge this with `VideoElement`? It got added in #1138 

Be sure to look at the existing methods. E.g., I think `VideoElement.within` would replace the `.videoSection` method here. ("within" is probably a better name)

2023-05-10 13:58 UTC, ChristopherChudzicki commented on tests-e2e/util/VideoSection.ts
> +   * @fakhar goal here is to scope other the selectors to this part of the DOM.
**Requested change:** Could you remove the `@fakhar` comment?

2023-05-10 13:58 UTC, ChristopherChudzicki commented on tests-e2e/util/index.ts
>  export { default as WwwPage } from "./WwwPage"
Ahh, the recently added VideoElement did not get added to these exports, or you probably would have noticed it. Oops.

2023-05-10 13:58 UTC, ChristopherChudzicki commented on tests-e2e/ocw-ci-test-course/shortcodes.spec.ts
> +test("Start and end times does not exist", async ({ page }) => {
**Requested Change:** Could you move these tests to `video.spec.ts`? They aren't really shortocde tests.

2023-05-10 13:58 UTC, ChristopherChudzicki requested changes
Looks good, a few small organization requests

2023-05-11 13:38 UTC, ChristopherChudzicki approved these changes
👍 Looks good. One suggestion, but up to you.

2023-05-11 13:38 UTC, ChristopherChudzicki approved these changes
👍 Looks good. One suggestion, but up to you.

2023-05-15 10:23 UTC, merged