OCW News Redesign
mitodl/ocw-hugo-themes pull request #1168
Opened 2023-06-06 14:09 UTC by ibrahimjaved12

#### Pre-Flight checklist

- [x] Screenshots and design review for any changes that affect layout or styling
  - [x] Desktop screenshots
  - [x] Mobile width screenshots
- [ ] Testing
  - [ ] Code is tested
  - [ ] Changes have been manually tested

#### What are the relevant tickets?
Closes https://github.com/mitodl/hq/issues/1388

#### What's this PR do?
This PR redesigns the OCW News portion of the homepage according to these designs:
[Mobile](https://www.figma.com/proto/MJPoWIwYmmJO0gFbGcZTcp/OCW-Homepage?page-id=288%3A1298&type=design&node-id=288-1299&viewport=683%2C483%2C0.72&scaling=min-zoom)
[Desktop](https://www.figma.com/proto/MJPoWIwYmmJO0gFbGcZTcp/OCW-Homepage?page-id=0%3A1&type=design&node-id=44-7&viewport=-277%2C1045%2C0.24&scaling=min-zoom&starting-point-node-id=89%3A2409
)

#### Review Steps
1. Checkout to this branch
2. `yarn start www`

Review will involve checking that the design does not break at any breakpoint. Images, text etc for featured news (the main big news on the left), as well as the news cards in the right side -- their title texts, images, etc.

In line 73, we have:
`{{ range $index, $item := after 1 (first 5 $items) }}
`
If we change `first 5 $items` to something like `first 10 $items`, then we can check for more news cards on the right side -- with different title texts, images of different size -- and we can confirm that they fit well.
And if we change it to something like `first 2 $items` we can also see that the design still works if we don't have enough items for the sidebar to display.

Similarly, in line 60 we have:
`{{ $firstItem := index $items 0 }}
`
For testing purposes, I would make the index 4 because index 4 image has bigger title and to check that truncating was done right.

Similarly, in line 26:
`                    {{ range $index, $newsItem := (first 5 $items) }}`
For mobile carousel view, if we change this to first 10 items we can have more items in the carousel and we can check that they display well.

Check that links redirect correctly to news items and the overall design is as expected.
There were some padding and font size etc related changes that had to be made to improve design after discussion with @mbilalmughal (that may be slightly different from figma designs).

#### Screenshots (if appropriate)
<img width="1306" alt="image" src="https://github.com/mitodl/ocw-hugo-themes/assets/109785089/81af719b-71d4-4aed-988c-0b97d0a03d68">
<img width="914" alt="image" src="https://github.com/mitodl/ocw-hugo-themes/assets/109785089/1f8387a2-8372-491d-901d-f66d2b57e2b4">
<img width="754" alt="image" src="https://github.com/mitodl/ocw-hugo-themes/assets/109785089/b519805b-230f-487f-a887-cea542d570af">

2023-06-19 10:15 UTC, HussainTaj-arbisoft requested changes
<img width="1305" alt="Screenshot 2023-06-19 at 2 43 45 PM" src="https://github.com/mitodl/ocw-hugo-themes/assets/71316217/106df669-04fe-46a2-82d4-3708c90e2194">

I would like to suggest some interactivity improvements.

In the desktop version, the yellow areas are not clickable. Making them clickable is the correct choice in my opinion.

The right-side elements are highlighted when a person hovers over them. However, they are only clickable when the hover is over the title or image. The hover effect and the ability to click should coincide. So, either only the title should trigger the hover effect, or the entire element should be clickable.

@mbilalmughal what do you think?

2023-06-19 10:42 UTC, pdpinch commented
Regarding alt text for images, the accessibility manager for Open Learning recommends against using alt text for decorative images, especially if it will be repetitive. 

If we get alt text in the news feed, we can use that. But if there is none, it's probably better to leave it empty, I.e., `alt=””`.

2023-06-27 07:58 UTC, ibrahimjaved12 commented on base-theme/assets/css/variables.scss
> +$featured-news-date-line-height: 1rem;
I think this requires re-evaluating the whole designs, the values used, everything etc. 

The same values may already have a variable, but it's name refers to some other use case -- so for that reason I could not use it. 
And also for the fact that in OCW News Redesign we actually have some different values at different breakpoints. Not all are already here also. 

I think this whole file of variables need a refactoring -- but that only comes with a re-evaluation of the designs and it's scope is out of scope for this PR. Like we need to have some fixed values to follow but we also need design representations that follow these. Only then we can have a thorough refactoring.

2023-06-27 08:07 UTC, ibrahimjaved12 commented on www/assets/css/home.scss
> +}
It is used for small screens. Without it you can see we don't have a margin between the buttons and the news image:
<img width="1347" alt="image" src="https://github.com/mitodl/ocw-hugo-themes/assets/109785089/14ff7e69-ee6a-4b76-b5b3-22b77b747aa3">
<img width="1342" alt="image" src="https://github.com/mitodl/ocw-hugo-themes/assets/109785089/d6158046-4e5f-4fce-9f9c-9129077892e9">

2023-06-30 15:48 UTC, ChristopherChudzicki commented
See also https://www.w3.org/WAI/tutorials/images/decorative/

2023-07-04 08:21 UTC, HussainTaj-arbisoft requested changes

2023-07-04 08:21 UTC, HussainTaj-arbisoft commented on www/layouts/partials/ocw_news.html
> +                      {{ $item.title.text | truncate 60 }}
Trim spaces in output
```suggestion
                      {{- $item.title.text | truncate 60 -}}
```

2023-07-04 11:18 UTC, ibrahimjaved12 commented on www/layouts/partials/ocw_news.html
> +                      {{ if (or (eq $modulo (sub $itemsInCarousel 1)) (eq $index (sub 5 1))) }}
I had tried getting rid of that equation in some other way but it was causing inconsistencies in the carousel animation. But that makes sense to use same condition for opening/closing tag. Good call getting rid of stale code.

2023-07-04 11:44 UTC, ibrahimjaved12 commented on www/layouts/partials/ocw_news.html
> +                      {{ $modulo := (mod $index $itemsInCarousel) }}
It appears modulo is not actually responsible here for getting back to 1st/Last item in the animation. Hence removed.

2023-07-04 12:29 UTC, HussainTaj-arbisoft approved these changes
LGTM 👍

2023-07-04 12:46 UTC, ibrahimjaved12 commented
> LGTM 👍

Thanks

2023-07-04 12:47 UTC, merged