adjust threshold down to 0.2 to filter out irrelevant results
mitodl/ocw-hugo-themes pull request #1183
Opened 2023-07-06 16:07 UTC by gumaerc

# What are the relevant tickets?
Closes https://github.com/mitodl/ocw-hugo-themes/issues/1182

# Description (What does it do?)
This PR simply adjusts the `threshold` value in the FuseJS configuration for offline search in `www-offline` to 0.2 from 0.4. After some testing, this seems to be a good place to set it in order to filter out irrelevant results.

# Screenshots (if appropriate):
![image](https://github.com/mitodl/ocw-hugo-themes/assets/12089658/2fee3dd8-771f-4efe-8f36-86fd015c5661)

# How can this be tested?
Follow the same instructions as https://github.com/mitodl/ocw-hugo-themes/pull/1175, but pay extra attention to the results and verify that irrelevant results have been minimized

2023-07-07 19:48 UTC, ChristopherChudzicki requested changes
In addition to the comment I left, one other requested change: Move `const searchResultsSection = document.getElementById("search-results")` above `performSearch`.

Currently, the `else` block throws an error since `searchResultsSection` is not defined. *Gosh, I forgot how easy these errors are in un-linted files.*

2023-07-10 17:29 UTC, ChristopherChudzicki requested changes
@gumaerc Did you want to add `ignoreLocation: true`? Currently, fuse is using the default values for distance/loc, so "Geographic Information Systems" still shows limited results.

**Requested change:**  As mentioned:  Move const searchResultsSection = document.getElementById("search-results") above performSearch.

Currently, the `else` block is throwing when there are no results.

2023-07-10 17:47 UTC, gumaerc commented
@ChristopherChudzicki Whoops, I missed that part but that makes sense. It should be all set now.

2023-07-10 17:57 UTC, ChristopherChudzicki approved these changes

2023-07-10 18:30 UTC, merged