change transcript start / end time test to use a different video
mitodl/ocw-hugo-themes pull request #1281
Opened 2023-11-15 00:09 UTC by gumaerc

# What are the relevant tickets?
Closes https://github.com/mitodl/ocw-hugo-themes/issues/1279

# Description (What does it do?)
This PR changes the "Transcripts start time matches video start time" test in `video.spec.ts` to use a different video resource. The video it was using started refusing to play in the Chromium browser, which Playwright uses on the backend to run its tests. Switching to another video solved the problem, but it is still unclear as to why the video will not play in Chromium anymore.

# How can this be tested?
 - Check out this branch locally
 - Make sure you don't have any values in your `.env` that would cause the end to end tests to fail. It may be best to back up your .env and run the tests with an empty one so it uses the defaults.
 - Run `yarn test:e2e` and verify that the tests pass

2023-11-15 14:40 UTC, ibrahimjaved12 reviewed
It appears the test is flaky now - failing about 5%-10% of the times. Reporting the same error as earlier "target is closed".
Replace `test()` with `test.only()` on the 5th test
And then run:
`yarn test:e2e video.spec --repeat-each=50`

For this, I don't think we would be able to explore what's happening using `--debug`. I think this could be one of those cases where playwright tries to do stuff really fast before the page stuff has fully loaded? We have had cases like these before. With exactly the same percentage of flakiness.

We need to investigate / modify the test case

2023-11-15 19:15 UTC, gumaerc commented
@ibrahimjaved12 I reverted this PR to use the original video from the test and swapped out the browsers being used for testing, since Chromium is being problematic with videos.

2023-11-16 13:14 UTC, ibrahimjaved12 requested changes
It looks like now we have 2 other tests failing, particularly in just `firefox`.
1. Verify that the 'Download video' and 'Download transcript' links are keyboard navigable and have the correct download URLs
```
Error: expect(received).toBe(expected) // Object.is equality

Expected: "https://live-qa.ocw.mit.edu/courses/123-ocw-ci-test-course-fall-2022/ocw_test_course_mit8_01f16_l01v01_360p_360p_16_9.mp4"
Received: null

  50 |     await page.keyboard.press("Tab")
  51 |     const hrefAttribute = await page.locator(":focus").getAttribute("href")
> 52 |     expect(hrefAttribute).toBe(downloadLinks[i])
     |                           ^
  53 |   }
  54 | })
  55 |

    at /Users/ibrahim.javed/MIT/ocw-hugo-themes/tests-e2e/ocw-ci-test-course/video-tabs.spec.ts:52:27
```
2. Video tabs content (links) are keyoard navigable
```
Test timeout of 30000ms exceeded.
Error: page.waitForURL: Navigation failed because page was closed!
=========================== logs ===========================
waiting for navigation to "**/courses/ocw-ci-test-course/resources/example_pdf/" until "load"
============================================================

  93 |     page.keyboard.press("Tab")
  94 |     page.keyboard.press("Enter")
> 95 |     await coursePage.page.waitForURL(`**/${tab.url}`)
     |                           ^
  96 |     expect(coursePage.page.url()).toContain(tab.url)
  97 |   }
  98 | })

    at /Users/ibrahim.javed/MIT/ocw-hugo-themes/tests-e2e/ocw-ci-test-course/video-tabs.spec.ts:95:27
```

Also, it appears the tests on Chrome run almost twice as fast as Firefox.
Despite that, I think it's useful that we are using both the browsers to run tests because firefox has actually pointed out good issues. (?)

Both the failed tests are pertaining to a lack of accessibility in those areas. I tested on my local firefox browser and I can confirm the behavior is same there.
Using tab on the `Download Video` button shifts focus to the next video tab -- Related resources, instead of "Download Transcript"
<img width="263" alt="image" src="https://github.com/mitodl/ocw-hugo-themes/assets/109785089/db5efc83-14c3-4b59-ab73-035741f7e213">

The other test expects (PDF link) to be clickable, but it seems that in Mac OS, using firefox leads to this problem -- that anchor tags are not keyboard clickable by default. Maybe the other problem is also related to that. There are fixes to this online -- that you can change your Mac settings / (or maybe firefox settings) but I don't see how that could be implemented for pw browser.

Do these problems occur in your linux firefox browser?

2023-11-16 14:41 UTC, ibrahimjaved12 approved these changes

2023-11-16 14:43 UTC, merged