Handle resource pages
mitodl/ocw-hugo-themes pull request #172
Opened 2021-09-07 19:08 UTC by noisecapella

#### Pre-Flight checklist

- [ ] Screenshots and design review for any changes that affect layout or styling
  - [ ] Desktop screenshots
  - [ ] Mobile width screenshots
- [ ] Testing
  - [ ] Code is tested
  - [ ] Changes have been manually tested

#### What are the relevant tickets?
Related to https://github.com/mitodl/ocw-studio/issues/508

#### What's this PR do?
TBD

#### How should this be manually tested?
TBD

2021-09-16 17:48 UTC, pdpinch requested changes
Screenshots are looking good, but there are two fields we can remove. 

I'll leave another comment about two fields that we want to add, but which may not be ready yet.

2021-09-16 17:48 UTC, pdpinch commented on course/layouts/partials/download_page.html
> +    </div>
we decided to remove course number because the same info is in the course info drawer.

2021-09-16 17:48 UTC, pdpinch commented on course/layouts/partials/download_page.html
> +    {{- end -}}
we decided to remove instructors because the same info is in the course info drawer.

2021-09-16 17:49 UTC, pdpinch commented
Two comments that are probably out of scope: 

1. This isn't in the design, but I think we want to display the `course_feature_tags` metadata. But maybe we should wait until after the field is renamed (https://github.com/mitodl/ocw-hugo-projects/issues/58)

2. We also want to add a license field (https://github.com/mitodl/ocw-hugo-projects/issues/45)

2021-09-16 19:11 UTC, noisecapella commented
Sure, I removed the two fields and I'll hold off on the other work. New screenshot:

![Screenshot from 2021-09-16 15-11-11](https://user-images.githubusercontent.com/863262/133671262-03a7efb4-f53d-4597-8e01-4a95a82084e0.png)

2021-09-20 15:29 UTC, noisecapella commented
@gumaerc I merged the ocw-to-hugo PR and referenced the new version in `package.json`

2021-09-20 20:10 UTC, gumaerc commented
So I just merged https://github.com/mitodl/ocw-hugo-themes/pull/192 so this needs a rebase based on that.  I tested locally accepting incoming changes for `ocw-to-hugo` 1.30.1 and everything worked great on my end.

2021-09-21 13:12 UTC, noisecapella commented
@gumaerc all set

2021-09-21 17:48 UTC, merged