Adjust level to new ocw-to-hugo format
mitodl/ocw-hugo-themes pull request #249
Opened 2021-10-29 18:19 UTC by noisecapella

#### Pre-Flight checklist

- [x] Testing
  - [x] Changes have been manually tested

#### What are the relevant tickets?
Related to https://github.com/mitodl/ocw-to-hugo/pull/398

#### What's this PR do?
`level` was changed to an array so this PR changes it to output one level link per item in the array

#### How should this be manually tested?
Convert a course with the latest ocw-to-hugo and view a course with this PR. The level in the course info on the course home page should look the same as before, with a link to the search page.

2021-11-01 18:17 UTC, gumaerc submitted a review, later dismissed
:+1: LGTM

2021-11-01 18:23 UTC, gumaerc commented
Actually, a caveat here.  After approving this I tested it with an `ocw-studio` published course and the build failed:

```
[start:course:hugo] Error: Error building site: failed to render pages: render of "page" failed: execute of template failed: template: pages/single.html:14:7: executing "pages/single.html" at <partialCached "mobile_course_info.html" .>: error calling partialCached: execute of template failed: template: partials/mobile_course_info.html:5:5: executing "partials/mobile_course_info.html" at <partial "course_info.html" (dict "context" . "inPanel" true)>: error calling partial: "/home/gumaerc/Code/ocw-hugo-themes/course/layouts/partials/course_info.html:56:30": execute of template failed: template: partials/course_info.html:56:30: executing "partials/course_info.html" at <$courseData.level>: range can't iterate over
```
It seems we need to make changes to the `ocw-course` starter in `ocw-hugo-projects` to match what was done here.  If those changes aren't made before this PR is merged and pushed to RC, builds there will start to fail.

2021-11-01 21:31 UTC, gumaerc requested changes
In order to be compatible with courses published from `ocw-studio` currently, we should make this compatible with both new and old versions of the data.

2021-11-01 21:31 UTC, gumaerc commented on course/layouts/partials/course_info.html
> +          {{ range $courseData.level }}
We should check if `$courseData.level` is an array here and only iterate it if that's the case.

2021-11-01 21:31 UTC, gumaerc commented on course/layouts/partials/course_info.html
> +          {{ $courseData.term }} {{ $courseData.year }}
We should check `if isset $courseData "year"` before trying to access it here

2021-11-02 16:03 UTC, noisecapella commented
@gumaerc all set

2021-11-02 16:41 UTC, gumaerc approved these changes
:+1: LGTM

It seems we don't actually need to check access on year.  I had it unset in my test course and didn't get any errors.

2021-11-02 21:07 UTC, merged