update home course cards instructors, topics and level
mitodl/ocw-hugo-themes pull request #269
Opened 2021-11-16 19:56 UTC by gumaerc

#### Pre-Flight checklist

- [ ] Testing
  - [ ] Changes have been manually tested

#### What are the relevant tickets?
Closes https://github.com/mitodl/ocw-hugo-themes/issues/267
Closes https://github.com/mitodl/ocw-hugo-themes/issues/268

#### What's this PR do?
In https://github.com/mitodl/ocw-studio/pull/449, we modified the `ocw-studio` REST API that the `home_course_cards.html` partial uses to get new courses to serialize instructor information alongside the UUID's of the instructors.  This changed the API schema to deliver objects for instructors instead of strings, which broke their display in the partial.  This PR creates a new partial called `home_course_cards_instructors.html` that is responsible for pulling these instructors out of the response and creating clickable search links for them to go in the card.  The same was done with topics as well as level, for better organization of the different parts of the cards that require a bit more processing.

#### How should this be manually tested?
 - Set `OCW_STUDIO_BASE_URL=http://ocw-studio-rc.odl.mit.edu/`
 - Run `npm run start:www`
 - Verify that instructors are displayed and are clickable links that go to `/search` with a proper query string
 - Verify the same thing for topics

2021-11-18 16:19 UTC, noisecapella requested changes

2021-11-18 16:19 UTC, noisecapella commented on www/layouts/partials/home_course_cards_topics.html
> +    {{- $topicLink := print "<a href=\"" $topicSearchUrl "\">" (title $topic) "</a>" -}}
Same comment here

2021-11-18 16:19 UTC, noisecapella commented on www/layouts/partials/home_course_cards_topics.html
> +    {{- $topicLink := print "<a href=\"" $topicSearchUrl "\">" (title $topic) "</a>" -}}
Same comment here

2021-11-18 20:54 UTC, gumaerc commented
@noisecapella I reworked the partials to not use the `print` command and instead keep track of the index for applying the commas so I don't have to use `delimit`.  Let me know what you think

2021-11-19 14:42 UTC, noisecapella approved these changes

2021-11-19 15:11 UTC, merged