Added CoPresent icon from google material design
mitodl/ocw-hugo-themes pull request #512
Opened 2022-03-10 15:17 UTC by Wassaf-Shahzad

#### Pre-Flight checklist

- [x] Screenshots and design review for any changes that affect layout or styling
  - [x] Desktop screenshots
- [x] Testing
  - [x] Changes have been manually tested

#### What are the relevant tickets?
Close #510 

#### What's this PR do?
Adds CoPresent icon for course features.

#### How should this be manually tested?
Verify proper icon shows up in learning resource type

#### Any background context you want to provide?
The CoPresent Icon was not available in out current icon library so I had top import the google material design font icon library and used the icon from it.
 
#### Screenshots (if appropriate)
<img width="1137" alt="Screenshot 2022-03-10 at 7 46 38 PM" src="https://user-images.githubusercontent.com/87968618/157692802-fdfcee9a-c675-467a-97b8-8690633c6bf6.png">

2022-03-10 15:32 UTC, dseaton commented
Looks good from a user perspective!

2022-03-10 19:10 UTC, alicewriteswrongs requested changes
this works great!

one thing though - if we're going to add another font, could we add it in the same way that the other icon fonts are already added? Check out the config in `webpack.common.js` and the font files saved in `base-theme/assets/fonts`. It's possible also if we just update the files in there that the `co_present` icon will be available for us, it looks like @gumaerc checked those files in to the repo last April.

2022-03-14 18:24 UTC, alicewriteswrongs approved these changes
LGTM! saw one small thing (blank line) you might want to address, feel free to merge after doing so

2022-03-14 18:24 UTC, alicewriteswrongs commented on base-theme/assets/css/main.scss
> +@mixin icon-styles {
nice touch with the mixin

2022-03-14 18:24 UTC, alicewriteswrongs commented on base-theme/layouts/partials/head.html
> +
stray blank line here

2022-03-15 04:44 UTC, Wassaf-Shahzad commented on base-theme/layouts/partials/head.html
> +
done

2022-03-16 13:08 UTC, merged