Updated the about page text
mitodl/ocw-hugo-themes pull request #522
Opened 2022-03-15 15:19 UTC by Wassaf-Shahzad

#### Pre-Flight checklist

- [x] Screenshots and design review for any changes that affect layout or styling
  - [x] Desktop screenshots
- [x] Testing
 - [x] Changes have been manually tested

#### What are the relevant tickets?
Closes #519 

#### What's this PR do?
Accomplishes the following
- [x] text changes 
- [x] fix the link: [Find courses with Instructor Insights](https://ocwnext.odl.mit.edu/search/?f=Instructor%20Insights&s=-runs.best_start_date)
- [x] update the "Dean's message" video to https://www.youtube.com/watch?v=1vSCB9V-Yqw
- [x] add Angela Pignatiello, Administrative Assistant to the OCW team  (until I locate a picture, you can use the same grey box as the one for Phil Sandy)
- [x] update the faculty advisory committee members

#### How should this be manually tested?
Verify all required changes mentions in issue #519 have been made.

#### Screenshots (if appropriate)
<img width="1440" alt="Screenshot 2022-03-15 at 8 04 01 PM" src="https://user-images.githubusercontent.com/87968618/158410683-12ca2ae6-60f7-438d-881b-f5331ec1650c.png">
<img width="1440" alt="Screenshot 2022-03-15 at 8 04 11 PM" src="https://user-images.githubusercontent.com/87968618/158410874-22131055-b750-43a9-9761-d0b60150b9d3.png">
<img width="1440" alt="Screenshot 2022-03-15 at 8 04 22 PM" src="https://user-images.githubusercontent.com/87968618/158410902-e2ba4c05-9cb4-48c9-a24f-72affe62d4bc.png">

2022-03-16 12:11 UTC, MAbdurrehman12 requested changes
Looks good. 
Noticed few things: I think, this might be something which can to be catered here.

1- Redbox: 2nd paragrapgh: 

Doc:
![image](https://user-images.githubusercontent.com/93309234/158583336-d3cb5abc-721d-434e-a3b9-2146470af6e0.png)

Site: 
![image](https://user-images.githubusercontent.com/93309234/158583558-ac12fa06-f9e1-4db6-99ab-0b0fbd686d56.png)

2- Milestones > 2001-2005: Document has 5 points where as site has 7 points, Do we have to match it with the document? As there's this note in the document: `** Note: text has generally been rewritten throughout the page.**` 
Same goes for 2006-2010, 2011-2015, 2016-2020: Number/Count of bullet points are not matching with the document.

2022-03-16 12:21 UTC, pdpinch requested changes
Please add / change the following images:

![Brett Paci](https://user-images.githubusercontent.com/430126/158588147-e1eec8cc-e8bf-41a0-b67b-ec45e8019077.jpg)

![Curt Newton](https://user-images.githubusercontent.com/430126/158588275-bee188cc-fee2-408b-9e56-1e5fa18b2186.jpg)

![Sarah Hansen](https://user-images.githubusercontent.com/430126/158588305-ce39a7ea-bc7e-4401-b22c-9034fd60d7f8.jpeg)


![Yunpeng Wang](https://user-images.githubusercontent.com/430126/158588411-9e3ae14f-5a99-4513-944f-d4f036c7802e.jpg)



![IMG_7579](https://user-images.githubusercontent.com/430126/158588451-f779e10a-9761-46a0-b1eb-549ebd01433a.jpg)

2022-03-16 12:21 UTC, pdpinch commented on www/content/milestones/2021.md
> +  - OCW celebrates its 20th anniversary, two decades of open sharing (video)
I think this should link to https://www.youtube.com/watch?v=8O2EPwUtWyY

2022-03-16 12:56 UTC, Wassaf-Shahzad commented
> Please add / change the following images:
> 
> ![Brett Paci](https://user-images.githubusercontent.com/430126/158588147-e1eec8cc-e8bf-41a0-b67b-ec45e8019077.jpg)
> 
> ![Curt Newton](https://user-images.githubusercontent.com/430126/158588275-bee188cc-fee2-408b-9e56-1e5fa18b2186.jpg)
> 
> ![Sarah Hansen](https://user-images.githubusercontent.com/430126/158588305-ce39a7ea-bc7e-4401-b22c-9034fd60d7f8.jpeg)
> 
> ![Yunpeng Wang](https://user-images.githubusercontent.com/430126/158588411-9e3ae14f-5a99-4513-944f-d4f036c7802e.jpg)
> 
> ![IMG_7579](https://user-images.githubusercontent.com/430126/158588451-f779e10a-9761-46a0-b1eb-549ebd01433a.jpg)

@pdpinch Can you also provide some meta data as well in regards to where to add them, their name and title.

2022-03-16 13:00 UTC, Wassaf-Shahzad commented
> Looks good. Noticed few things: I think, this might be something which can to be catered here.
> 
> 1- Redbox: 2nd paragrapgh:
> 
> Doc: ![image](https://user-images.githubusercontent.com/93309234/158583336-d3cb5abc-721d-434e-a3b9-2146470af6e0.png)
> 
> Site: ![image](https://user-images.githubusercontent.com/93309234/158583558-ac12fa06-f9e1-4db6-99ab-0b0fbd686d56.png)
> 
> 2- Milestones > 2001-2005: Document has 5 points where as site has 7 points, Do we have to match it with the document? As there's this note in the document: `** Note: text has generally been rewritten throughout the page.**` Same goes for 2006-2010, 2011-2015, 2016-2020: Number/Count of bullet points are not matching with the document.

@pdpinch @MAbdurrehman12, I just updated the text of the points in milestones  and did not remove any point. As the doc did not explicitly say to remove any point.
I just need some confirmation if I can remove  points in milestones which are not mentioned in document

2022-03-16 13:29 UTC, pdpinch commented
> I just need some confirmation if I can remove points in milestones which are not mentioned in document

Yes, please remove the points that don't appear in the updated doc.

2022-03-16 14:54 UTC, pdpinch commented
@Wassaf-Shahzad here's the issue for the home page link. I think you said you wanted to add it to this PR.

2022-03-16 14:55 UTC, pdpinch commented
The new images are all people who are already on the page:

- [ ] [Brett Paci](https://user-images.githubusercontent.com/430126/158588147-e1eec8cc-e8bf-41a0-b67b-ec45e8019077.jpg)
- [ ] [Curt Newton](https://user-images.githubusercontent.com/430126/158588275-bee188cc-fee2-408b-9e56-1e5fa18b2186.jpg)
- [ ] [Sarah Hansen](https://user-images.githubusercontent.com/430126/158588305-ce39a7ea-bc7e-4401-b22c-9034fd60d7f8.jpeg)
- [ ] [Yunpeng Wang](https://user-images.githubusercontent.com/430126/158588411-9e3ae14f-5a99-4513-944f-d4f036c7802e.jpg)
- [ ] [Angela Pignatiello](https://user-images.githubusercontent.com/430126/158588451-f779e10a-9761-46a0-b1eb-549ebd01433a.jpg)

2022-03-17 12:34 UTC, Wassaf-Shahzad commented
> @Wassaf-Shahzad here's the issue for the home page link. I think you said you wanted to add it to this PR.

Also added changes needed for issue #524

2022-03-18 01:12 UTC, pdpinch requested changes
another round of text edits, based on the changes in https://docs.google.com/document/d/1HUivXOfS1bovVAJX2u_2QERqUSlU9dG2uQiC0vVIqDA/edit?pli=1

When the PR is updated I'll ask them to review on netlify again

2022-03-18 01:12 UTC, pdpinch commented on www/content/milestones/2016-2020.md
> +  - OCW becomes the most-subscribed .edu channel on YouTube.
add link to https://www.youtube.com/c/mitocw

```suggestion
  - OCW becomes the most-subscribed .edu channel on [YouTube](https://www.youtube.com/c/mitocw).
```

2022-03-18 01:12 UTC, pdpinch commented on www/content/milestones/2016-2020.md
>    - Interactive, searchable transcripts are added to videos.
remove these two lines
```suggestion
```

2022-03-18 01:12 UTC, pdpinch commented on www/content/milestones/2016-2020.md
>    - New MIT Open Learning Library launches in 2019, offering new, self-paced learning options complementing OCW and MITx.
link to https://openlearning.mit.edu/courses-programs/open-learning-library
```suggestion
  - New [MIT Open Learning Library](https://openlearning.mit.edu/courses-programs/open-learning-library) launches in 2019, offering new, self-paced learning options complementing OCW and MITx.
```

2022-03-18 01:12 UTC, pdpinch commented on www/content/milestones/2016-2020.md
>    - Chalk Radio podcast launches in February 2020.
add link
```suggestion
  - [Chalk Radio podcast](https://chalk-radio.simplecast.com/) launches in February 2020.
```

2022-03-18 01:12 UTC, pdpinch commented on www/content/milestones/2016-2020.md
> +  - OCW website traffic nearly doubles as the COVID-19 pandemic disrupts life around the world.
```suggestion
  - OCW supports learners around the world as the COVID-19 pandemic disrupts education.
```

2022-03-18 01:12 UTC, pdpinch commented on www/content/milestones/2021.md
>  image: /images/about/timeline-image-1.png
the title should be `2021+`

2022-03-18 01:12 UTC, pdpinch commented on www/content/milestones/2021.md
> +  - "New OCW platform launches: mobile responsive, enhanced search and more"
```suggestion
  - OCW celebrates its 20th anniversary and two decades of open sharing ([video](https://www.youtube.com/watch?v=8O2EPwUtWyY)).
  - New OCW platform launches: mobile responsive, enhanced search and more
  - 440 OCW mirror sites around the world.
```

2022-03-18 01:12 UTC, pdpinch commented on www/layouts/about/section.html
>                >Find course with Instructor Insights</a
```suggestion
              >Find courses with Instructor Insights</a
```

2022-03-18 08:04 UTC, Wassaf-Shahzad commented on www/content/milestones/2001-2005.md
>    - The first [OCW mirror site](https://ocw.mit.edu/about/mirror-site-program/) is established in Africa.
Which link ?

2022-03-18 09:34 UTC, Wassaf-Shahzad commented
Updated text and also included changes for issue #530

2022-03-18 12:04 UTC, pdpinch commented on www/content/milestones/2001-2005.md
>    - The first [OCW mirror site](https://ocw.mit.edu/about/mirror-site-program/) is established in Africa.
```suggestion
  - The first OCW mirror site is established in Africa.
```

2022-03-18 12:13 UTC, pdpinch requested changes
Thanks. I know that was a lot of small text changes, but it looks like you missed a couple:

- [ ] https://github.com/mitodl/ocw-hugo-themes/pull/522/files#r829622620
- [ ] https://github.com/mitodl/ocw-hugo-themes/pull/522/files#r829622412
- [ ] https://github.com/mitodl/ocw-hugo-themes/pull/522/files#r829621858
- [ ] https://github.com/mitodl/ocw-hugo-themes/pull/522/files#r829618940

2022-03-18 12:31 UTC, Wassaf-Shahzad commented
> Thanks. I know that was a lot of small text changes, but it looks like you missed a couple:
> 
> * [ ]  https://github.com/mitodl/ocw-hugo-themes/pull/522/files#r829622620
> * [ ]  https://github.com/mitodl/ocw-hugo-themes/pull/522/files#r829622412
> * [ ]  https://github.com/mitodl/ocw-hugo-themes/pull/522/files#r829621858
> * [ ]  https://github.com/mitodl/ocw-hugo-themes/pull/522/files#r829618940

Ohh sorry, for some reason, these changes were showing up as `Hidden conversation` for me. So I missed them.
Addressed them as well

2022-03-18 13:05 UTC, pdpinch requested changes
one more tiny change

2022-03-18 13:05 UTC, pdpinch commented on www/layouts/about/section.html
> +            users fully into OCW's global community… provides more powerful
sorry, I mistakenly added a space here after the `...`. please remove. 
```suggestion
            users fully into OCW's global community…provides more powerful 
```

2022-03-21 21:40 UTC, pdpinch approved these changes
The copy is good. Let's merge this. 

There may be updates to the images later, but this is good enough for release. 

Thank you for your patience!

2022-03-22 12:48 UTC, merged