fix: browse course material button styling
mitodl/ocw-hugo-themes pull request #611
Opened 2022-04-05 12:05 UTC by MAbdurrehman12

#### Pre-Flight checklist

- [x] Screenshots and design review for any changes that affect layout or styling
  - [x] Desktop screenshots
  - [x] Mobile width screenshots
- [x] Testing
  - [x] Code is tested
  - [x] Changes have been manually tested

#### What are the relevant tickets?
Closes https://github.com/mitodl/ocw-hugo-themes/issues/606

#### What's this PR do?
- Changes the style of `browse course material` button according to issue ticket and invision design

#### How should this be manually tested?
- Checkout this branch
- Build any course(s) locally
- Go to a smaller screen size (tablet or less)
- Verify that the style `browse course material` button is correct.

#### Screenshots (if appropriate)
<img width="822" alt="image" src="https://user-images.githubusercontent.com/93309234/161749646-c6bf6b58-155f-4c5b-9748-6986b8c37bb1.png">

<img width="513" alt="image" src="https://user-images.githubusercontent.com/93309234/161749688-c9f9ecef-0c3a-4c8a-8e6b-1f4fa5f2d3fd.png">

<img width="346" alt="image" src="https://user-images.githubusercontent.com/93309234/161749773-44fe3010-b2cd-476f-a532-542bde99bddc.png">

2022-04-05 16:35 UTC, abeglova commented
This works but it looks like the mobile design no longer has a top border line above the button. I think that looks better than keeping that border

2022-04-05 16:37 UTC, abeglova requested changes
One comment about the border line. Also, there is a lot of variation in how much whitespace there is around the "browse course materials button"

2022-04-05 16:43 UTC, MAbdurrehman12 commented
> This works but it looks like the mobile design no longer has a top border line above the button. I think that looks better than keeping that border

The border is not with this `course material` button, it's with/below the heading section, and since it wasn't mentioned in the issue ticket so I did not remove it despite the fact it's not there in the design but I can remove it if you think it will look better without the border.  

> there is a lot of variation in how much whitespace there is around the "browse course materials button"

Not sure if I follow this. Variation in different screen sizes?

2022-04-05 16:45 UTC, pdpinch commented
> The border is not with this course material button, it's with/below the heading section, and since it wasn't mentioned in the issue ticket so I did not remove it despite the fact it's not there in the design but I can remove it if you think it will look better without the border.

If it's not too much trouble, please remove it. The button is enough of a visual separator. We don't need a line as well.

2022-04-05 17:49 UTC, abeglova commented
The variation is by page type: The button has less white space around it on course home pages than resource pages

2022-04-06 10:07 UTC, MAbdurrehman12 commented
@abeglova Thanks for reviewing and pointing out these things. 
I have removed the borderline on resources pages and added some space around the button in course home page.
Can you please have another look?

btw, I think there is an inconsistency in right/left spacing in course home page and resources pages. (course home page has more space on the left and right sides as compared to resource pages)

e.g:
course home page: 
<img width="85" alt="image" src="https://user-images.githubusercontent.com/93309234/161951682-d43d1dc7-3202-41db-b81b-1e335a00d13f.png">

resource page:
<img width="94" alt="image" src="https://user-images.githubusercontent.com/93309234/161951503-79e9e0cb-2bc5-4962-a3ab-4be00f6570ab.png">

not sure if this is something that needs to be catered too.

2022-04-06 13:52 UTC, abeglova approved these changes
LGTM

2022-04-06 14:11 UTC, merged