search API error handling improved
mitodl/ocw-hugo-themes pull request #761
Opened 2022-06-22 11:47 UTC by MAbdurrehman12

#### Pre-Flight checklist

- [x] Screenshots and design review for any changes that affect layout or styling
  - [x] Desktop screenshots
  - [ ] Mobile width screenshots
- [x] Testing
  - [x] Code is tested
  - [x] Changes have been manually tested

#### What are the relevant tickets?
Closes https://github.com/mitodl/ocw-hugo-themes/issues/736

#### What's this PR do?
- Sends additional data for better debugging when search API fails.
    - Tags added: 
        1. API response status
        2. API response status text
        3. Current URL with query params
    - Level set to "Error"
    - Extras: Search Query Params
- **Note:** I spent some time but was unable to debug the actual cause of why the issue is occurring in the first place. Hence the error message has been improved by which I think we will be in a better position to debug the issue.

#### How should this be manually tested?
- Go to the search page. (If having CORs issue then [run chrome without cors](https://alfilatov.com/posts/run-chrome-without-cors/))
- Test and verify that everything is working as expected.
- Now we want the API to fail, this can be done by any method (give an invalid URL, let the code break from any other method etc)
- Verify that now an error msg is shown to the user and an event is logged in sentry with the following details/info:
    - Event does not have `<unknown>` title.
    - Similar events are grouped/merged into one. 
    - Current URL with query params tag (for quick testing)
    - API response status tag.
    - API response status text tag
    - Level: Error tag
    - Search Query Params
- Any use-case which needs to be tested.

#### Screenshots

<img width="1172" alt="image" src="https://user-images.githubusercontent.com/93309234/175021646-02b8fcd5-1d75-4f01-96f7-02e9003a87a7.png">

<img width="847" alt="image" src="https://user-images.githubusercontent.com/93309234/175021515-e1bb5eda-0500-45ee-b6d9-9332f9f51fe3.png">

<img width="875" alt="image" src="https://user-images.githubusercontent.com/93309234/175021570-55140cb7-ce3d-4c30-8a4d-76ab7d25d6c2.png">

2022-06-23 10:31 UTC, Wassaf-Shahzad requested changes

2022-06-23 10:31 UTC, Wassaf-Shahzad commented on www/assets/js/lib/util.ts
> +  Sentry.captureException(message, additionalData)
Shouldn't this be capture message ?

2022-06-23 12:08 UTC, MAbdurrehman12 commented on www/assets/js/lib/util.ts
> +  Sentry.captureException(message, additionalData)
oops

2022-06-24 11:39 UTC, Wassaf-Shahzad approved these changes
LGTM!

2022-06-24 11:41 UTC, MAbdurrehman12 commented
@pdpinch Do you want to have a look into this PR, in case you have any thoughts/suggestions or should we merge it?

2022-06-24 20:24 UTC, pdpinch approved these changes
LGTM, AFAICT 
👍

2022-06-24 20:25 UTC, merged