feat: compact design
mitodl/ocw-hugo-themes pull request #784
Opened 2022-07-01 15:52 UTC by MAbdurrehman12

#### Pre-Flight checklist

- [ ] Screenshots and design review for any changes that affect layout or styling
  - [ ] Desktop screenshots
  - [ ] Mobile width screenshots
- [ ] Testing
  - [ ] Code is tested
  - [ ] Changes have been manually tested

#### What are the relevant tickets?
Closes https://github.com/mitodl/ocw-hugo-themes/issues/765

#### What's this PR do?
- Will provide details once PR is finalized and up for review.

#### How should this be manually tested?
- Will provide testing instructions once PR is finalized and up for review.

#### Screenshots (if appropriate)
- Coming soon....

2022-07-04 16:01 UTC, pdpinch commented
@Wassaf-Shahzad how/can I see this PR deployed with a course?

2022-07-04 19:28 UTC, MAbdurrehman12 commented
> how/can I see this PR deployed with a course?

@pdpinch This is a [deployed course](https://ocw-hugo-themes-course-pr-784--ocw-next.netlify.app/). But the PR is not fully ready yet so there are things that will not seem right yet.

2022-07-05 11:45 UTC, Wassaf-Shahzad commented
> 🚀 Deployed on https://ocw-hugo-themes-course-pr-784--ocw-next.netlify.app

@pdpinch This one

2022-07-06 12:19 UTC, MAbdurrehman12 commented
@pdpinch Currently, I'm testing multiple courses locally and trying to find issues but I think you can also take a look and if anyone wants to review the code, that is fine too.

2022-07-18 12:59 UTC, MAbdurrehman12 commented on course-v2/layouts/partials/course_info.html
> +function desktopCourseInfoToggle(){
I'm making a follow-up PR for https://github.com/mitodl/ocw-hugo-themes/issues/795 and will change this approach along with moving this code to a suitable place.

2022-07-19 13:10 UTC, Wassaf-Shahzad commented
@pdpinch Should there be better spacing between table headings and rows

<img width="1171" alt="Screenshot 2022-07-19 at 6 00 20 PM" src="https://user-images.githubusercontent.com/87968618/179757960-74e18cd7-767b-4af3-a877-4e135a917e25.png">

2022-07-19 16:05 UTC, pdpinch commented
> @pdpinch Should there be better spacing between table headings and rows

I don't think the designs include any updates to the table headings and rows. 

@Wassaf-Shahzad what are you suggesting we should change?

2022-07-20 10:34 UTC, Wassaf-Shahzad commented
> > @pdpinch Should there be better spacing between table headings and rows
> 
> I don't think the designs include any updates to the table headings and rows.
> 
> @Wassaf-Shahzad what are you suggesting we should change?



> #765

what I am inquiring is whether we should increase the spacing between table row and table heading as they currently looked a bit squished (as shown ) on the screenshot above.

2022-07-20 10:52 UTC, Wassaf-Shahzad requested changes
Looks and works great ! Just some minor things
- Some files dont end with a new line, those should be added
- Tables are not responsive, I checked this behaviour upto 320px which is the recommended smallest screen size. Screen shots attached
- Footer also behaves differently on small screens

### Tables on ocwnext
<img width="1171" alt="Screenshot 2022-07-20 at 3 34 59 PM" src="https://user-images.githubusercontent.com/87968618/179964778-b7048c9a-e0ea-409c-a70d-e45725f6fd27.png">

### Tables on course-v2
<img width="1160" alt="Screenshot 2022-07-20 at 3 47 03 PM" src="https://user-images.githubusercontent.com/87968618/179964804-d6f32580-8427-4193-9222-f6b458490d56.png">

2022-07-20 20:52 UTC, gumaerc commented
@Wassaf-Shahzad @MAbdurrehman12  In the console you see this error:

```
(index):1814 Uncaught TypeError: Cannot read properties of null (reading 'getElementsByTagName')
    at initResponsiveTables ((index):1814:80)
    at (index):1814:512
```

It seems this is because the script that does this was looking for the div with the `id` of `main-content`, which doesn't seem to exist anymore.  Instead it seems that a div with the class `course-home-content` is the top level div in the content area, even when you're not on the course home page.  We need to assign an ID again to the outer element in the content area and make sure it matches what's in the script.

![image](https://user-images.githubusercontent.com/12089658/180079032-b7ee6d5b-4c4b-4714-a518-1dcbd95c4eb8.png)

2022-07-20 21:13 UTC, MAbdurrehman12 commented
Thanks for looking into this @gumaerc @Wassaf-Shahzad 
I'll update the PR tomorrow

2022-07-25 13:12 UTC, Wassaf-Shahzad commented
LGTM ! but you should still wait for @gumaerc if he has any input

2022-07-25 20:09 UTC, gumaerc requested changes
Overall this looks very good.  As I noted in https://github.com/mitodl/ocw-hugo-themes/pull/803, it seems that we have not isolated the changes to the header and footer to `course-v2.`  I think we'll want to create v2 versions of both the header and the footer in `base-theme` and use those in `course-v2` instead.  You can see that when I use this branch locally while only specifying `["course", "base-theme"]` as  my themes in my config, I get the new header and footer when using the old theme:

![image](https://user-images.githubusercontent.com/12089658/180865379-e6f78634-e81d-4d70-bf34-ec95a90ddcc5.png)

![image](https://user-images.githubusercontent.com/12089658/180865418-40242ba4-67ad-4fdc-bb61-cf6f32d92af9.png)

vs live production:

![image](https://user-images.githubusercontent.com/12089658/180865472-e5e3902d-2ff9-455d-b6de-453faa222303.png)

![image](https://user-images.githubusercontent.com/12089658/180865515-ed76dd78-3d14-44c4-a21e-2b13aab7cd29.png)

2022-07-27 12:39 UTC, MAbdurrehman12 commented
@gumaerc instead of creating separate files for header and footer, I have overridden some CSS in course-v2 theme as I had some issues in creating separate files and this approach (of overriding CSS) also looked quite simple.
I have also added this comment that when we completely roll out to new theme then we can get rid of this overridden CSS.

Apart from this, the new theme also has a different logo, which I did not change/replace with the old one as this logo is much clearer.

Can you please have another look? and let me know if you find out any issue.

Thanks

2022-07-27 14:00 UTC, gumaerc requested changes
The CSS changes are a fine approach.  There are only a couple other things I noticed:

 - The logo image has been replaced with a smaller version and the original version has not been preserved, so you get the smaller logo image when rendering with the old theme:
 
![image](https://user-images.githubusercontent.com/12089658/181265726-400dc7f0-3f4a-41fb-a303-0ae37f7c0ba2.png)

vs

![image](https://user-images.githubusercontent.com/12089658/181265858-8f20dc86-f103-4704-9eee-39c11c54f96f.png)

 - You've been doing a good job commenting, but it would be nice if we could leave a marker, something like `TODO: course-v2` wherever inline code changes like the header / footer CSS will need to be reconciled when it comes time to merge this into `course`.  That way, we have a consistent tag we can search for to easily locate all the places where we couldn't simply just override the existing layout in the `course-v2` folder.

2022-07-27 20:27 UTC, gumaerc approved these changes
:+1: LGTM!

2022-07-27 20:30 UTC, merged

2022-10-11 08:21 UTC, pdpinch commented
Do we not have tests for the responsive function? 

> On Jul 20, 2022, at 6:52 AM, Wassaf-Shahzad ***@***.***> wrote:
> 
> Tables are not responsive, I checked this behaviour upto 320px which is the recommended smallest screen size. ScreenShots attached