fixed issue with lighthouse
mitodl/ocw-hugo-themes pull request #785
Opened 2022-07-05 11:53 UTC by Wassaf-Shahzad

#### Pre-Flight checklist

- [X] Testing
  - [X] Code is tested

#### What are the relevant tickets?
No tickets

#### What's this PR do?
Fixes url for lighthouse

#### How should this be manually tested?
verify lighthouse stats are shown

2022-07-11 22:09 UTC, gumaerc requested changes
There seems to be an unrelated change in this PR, might be best to rebase it off of `main`:

2022-07-11 22:09 UTC, gumaerc commented on package.json
> +    "webpack": "^5.73.0",
Why are we upgrading webpack in this PR?  Did you base your initial branch off of https://github.com/mitodl/ocw-hugo-themes/pull/787?  This PR should be based off of `main` and should only make the change that you made in `.github/workflows/deploy.yml`.

2022-07-12 14:39 UTC, Wassaf-Shahzad commented
> There seems to be an unrelated change in this PR, might be best to rebase it off of `main`:

Yeah it had some unwanted commits I have removed those and is ready to merge

2022-07-12 14:46 UTC, gumaerc approved these changes
:+1: LGTM

2022-07-12 14:47 UTC, merged