sidebar and image section height and width styling
mitodl/ocw-hugo-themes pull request #814
Opened 2022-08-05 10:52 UTC by MAbdurrehman12

#### Pre-Flight checklist

- [x] Screenshots and design review for any changes that affect layout or styling
  - [x] Desktop screenshots
  - [ ] Mobile width screenshots
- [x] Testing
  - [x] Code is tested
  - [x] Changes have been manually tested

#### What are the relevant tickets?
closes https://github.com/mitodl/ocw-hugo-themes/issues/811

#### What's this PR do?
- Makes the height of all 3 sections on CHP the same
- Increases the width of course image section on home page

#### How should this be manually tested?
- Build any v2 course locally.
- Verify the above-mentioned points on multiple browsers and screen dimensions.

#### Screenshots
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/93309234/183062757-713a94d6-2efb-4968-90f5-7433b9b724fb.png">

2022-08-15 11:21 UTC, Wassaf-Shahzad requested changes
LGTM!, I just had one concern, The panel on the right most side takes about 25% for the available space. Should it be smaller ?
![Screenshot 2022-08-15 at 4 19 03 PM](https://user-images.githubusercontent.com/87968618/184626453-87a6db4c-6268-4712-889f-f7698c71c4f8.png)

2022-08-15 12:29 UTC, MAbdurrehman12 commented
> The panel on the right most side takes about 25% for the available space. Should it be smaller

This PR was created to increase its width, as initially, its width was smaller but then it was pointed out. 
See the [issue ticket](https://github.com/mitodl/ocw-hugo-themes/issues/811) and the [design](https://projects.invisionapp.com/d/main?origin=v7#/console/21537330/467361595/preview).
Though I agree, as compared to the design, its width is a bit larger but this difference is due to the usage of the bootstrap grid system here (we are not using our own `px` values). Since bootstrap cols have their own width and I'd suggest not overriding them for better consistency across the app.
but if I'm being mistaken or the width should be smaller, please let me know.

Maybe if @Ferdi  @pdpinch @gumaerc has any thoughts?

2022-08-15 20:47 UTC, pdpinch commented
In the design, the image width is 361px, so this is definitely too wide. Can we reduce it from 4 columns to 3? Or is there some other way to target the image width on a desktop?

2022-08-16 09:52 UTC, MAbdurrehman12 commented
> Can we reduce it from 4 columns to 3? 

Previously, it was set to 3 columns (have a look [here](https://live-qa.ocw.mit.edu/course-v2/courses/wgs-s10-special-topics-in-women-gender-studies-seminar-latina-womens-voices-spring-2010/)), but then to increase its width, I changed it to 4 columns in this PR.
But if you think that it looks fine with 3 columns, then maybe we can change it back to 3?

> is there some other way to target the image width on a desktop?

1 approach is to use bootstrap (already using).
Another approach is to use CSS to make our own grids and custom width etc, for that, we'll also have to cater the responsiveness by using media queries etc. 
My suggestion would be to stick with bootstrap but if we really want to have the exact width, we can proceed with writing our own CSS.

(btw I'm talking about the width of the complete image section, not just the image only)

2022-08-16 16:39 UTC, gumaerc commented
@MAbdurrehman12 Another thing we could try is overriding the SASS variables used to construct the bootstrap styles. Bootstrap columns are constructed based on percentages using flexbox, so while you wouldn't want to give a column a specific width, you can adjust the total amount of columns in a grid.  The default is 12, but you can [override it](https://getbootstrap.com/docs/4.0/layout/grid/#customizing-the-grid):

```
$grid-columns: 12 !default;
$grid-gutter-width: 30px !default;
$grid-breakpoints: (
  xs: 0,
  sm: 480px,
  md: 768px,
  lg: 1024px
);

$container-max-widths: (
  sm: 420px,
  md: 720px,
  lg: 960px
);
```

We have a bootstrap overrides file at `base-theme/assets/css/bootstrap-overrides.scss`. We should be able to override the `$grid-columns` variable to increase the total number of columns, increasing the granularity of each column and giving us finer control.

2022-08-17 09:39 UTC, MAbdurrehman12 commented
> we could try is overriding the SASS variables used to construct the bootstrap styles

Yeah, I had this in mind but didn't proceed with it to maintain consistency in bootstrap styles: Changing them globally will have a widespread impact, so we can only change it for this section (not sure if it'll be a good approach).

> you can adjust the total amount of columns in a grid

I gave this a shot but it looks like the exact/close to exact width is still not being achieved by adjusting the columns. As reducing a column makes it a bit small and increasing the column makes it a bit large, lol. Adjusting columns also have an impact on the other sections (side navbar, course description section).

I think if the initial width, which can be seen [here](https://live-qa.ocw.mit.edu/course-v2/courses/wgs-s10-special-topics-in-women-gender-studies-seminar-latina-womens-voices-spring-2010/), is not up to the mark, then I'll just go on and override bootstrap col width for CHP only to achieve the exact width as mentioned in the design.

Maybe @pdpinch can share his thoughts on this?

2022-08-18 13:09 UTC, pdpinch commented
pixel-perfect is not a concern, but "too wide" is a concern.

2022-08-22 10:46 UTC, MAbdurrehman12 commented
@gumaerc Your point of having 100 `grid columns` and considering `col` as a percentage makes sense. 
I'm having some trouble applying this change only to CHP (since `$grid-columns` are fetched and defined on the compilation I think) as I don't think it will be a good idea to make this change globally as it will have quite a widespread impact. 
Do you have any possible solution in mind?

After this, we can identify the percentage of the `image` section, along with the `side-navbar` and `course description` section from the design and use them.
Currently, in design, it looks like that image section is taking up to 31-32% of the total grid. 
and if we look into this PR, we have assigned `4 cols`, out of 12, to the image section which is 33% ((4/12)*100).

So I wonder, even after, applying the 100 `grid columns` approach, the result will almost be the same. 
and if 31-33% is too wide, then do we need to get the design updated? or I'm missing something? 

(its not looking too wide in the design since maybe the overall design width is a bit narrow?)

2022-08-22 11:13 UTC, gumaerc commented
@MAbdurrehman12 It was just a suggestion of something to try out. Like you pointed out, it seems we're already getting pretty close to the ratio we want so it may not be worth the extra work to re-work `$grid-columns`. If it needs to be more precise than it is, maybe we just want to write some custom CSS to do so. We will have to do responsive breakpoints manually though.

2022-08-22 12:45 UTC, MAbdurrehman12 commented
I'll just go on, remove bootstrap cols and add custom CSS to be more precise.

2022-08-30 10:13 UTC, Wassaf-Shahzad approved these changes
Works great !

2022-08-31 10:02 UTC, MAbdurrehman12 commented
>  At larger mobile resolutions, the course image is still visible. In the current course theme, we hide the course image at these resolutions

Thanks for pointing this out @gumaerc. 
I've now also hidden the course image section on smaller screens to make it the same as in the current course theme. 
I think, now we can merge this PR!

2022-08-31 10:27 UTC, merged