hide download button if zip doesn't exist v2
mitodl/ocw-hugo-themes pull request #979
Opened 2022-11-14 22:08 UTC by gumaerc

#### Pre-Flight checklist

- [ ] Screenshots and design review for any changes that affect layout or styling
  - [ ] Desktop screenshots
  - [ ] Mobile width screenshots
- [ ] Testing
  - [ ] Code is tested
  - [ ] Changes have been manually tested

#### What are the relevant tickets?
(Required)

#### What's this PR do?
(Required)

#### How should this be manually tested?
(Required)

#### Where should the reviewer start?
(Optional)

#### Any background context you want to provide?
(Optional)

#### Screenshots (if appropriate)
(Optional)

2022-11-15 17:44 UTC, ChristopherChudzicki requested changes
@gumaerc I will test this after lunch, but left two comments about GO templating.

I spent some time this morning trying to understand GO templates a little better. The demos athttps://github.com/mitodl/ocw-hugo-themes/issues/949#issuecomment-1315635533 may be of interest.

2022-11-15 17:44 UTC, ChristopherChudzicki commented on course-v2/layouts/partials/resources_header.html
> +        <a class="download-course-button p-2" href="{{- $downloadCourseUrl -}}">
This change is unnecessary and imo we should skip it:
- `{{-` trims whitespace to the left of `{{`. The next leftwards character is `"`, not whitespace, so this change does nothing.
- `-}}` trims whitespace to the right of `}}`. The next rightwards character is `"`, not whitespace, so this change does nothing.

2022-11-15 22:18 UTC, ChristopherChudzicki reviewed
@gumaerc This looks good to me, aside from the trimming issue I pointed out (which I do think should be changed).

As discussed in Slack, I had trouble testing this locally with the written instructions. Instead, I:
1. Publish course to my private github or, so the github markdown has short-id
2. run ocw-hugo-themes using the repo from my private org
3. In the template, manually change trimmedBaseUrl to {{- $trimmedBaseUrl := "courses/9-40-introduction-to-neural-computation-spring-2018" -}} 
4. run yarn start course w/ STATIC_API_BASE_URL pointing at ocw.mit.edu ... download button shows
5. Repeat 1–4 with an invalid trimmedBaseUrl, no download button.

2022-11-16 00:04 UTC, gumaerc commented
@ChristopherChudzicki Thanks for the review. I've made the whitespace delimiting changes and updated the testing instructions to reflect your experience you detailed above. I was able to test this locally by first building `ocw-www` with a `STATIC_API_BASE_URL` pointing to rc or prod, then switch it to the internal docker IP for building the course site. The course site build will be able to get instructors from your locally built `ocw-www` at that point, and the check for the ZIP file will be performed against your Minio instance as expected.

2022-11-16 13:23 UTC, ChristopherChudzicki approved these changes

2022-11-16 13:50 UTC, merged